version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - quantco/ci
    groups:
      gh-actions:
        patterns:
          - "*"
