{% set name = "tabmat" %}

package:
  name: {{ name|lower }} 
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}{% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}.post{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}{% endif %}

source:
  git_url: ../


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - cython
    - jemalloc-local  # [not win]
    - llvm-openmp  # [osx]
    - mako
    - numpy
    - pip
    - setuptools_scm
    - xsimd
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tabmat

about:
  home: https://github.com/Quantco/tabmat
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Efficient matrix representations for working with tabular data '
  description: |
    tabmat provides efficient tools for representing tabular data as a mix of
    dense, sparse and categorical subcomponents, resulting in 100x faster 
    performance on some machine learning problems!
  doc_url: https://tabmat.readthedocs.io/
  dev_url: https://github.com/Quantco/tabmat

extra:
  recipe-maintainers:
    - MarcAntoineSchmidtQC
    - xhochy
    - tbenthompson
