name: conda-build macOS
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  macos-conda-build:
    name: "MacOS - conda-build - ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: macos-latest
    env:
      CI: True
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - osx_64_python3.7_default.____cpython
          - osx_64_python3.8_default.____cpython
          - osx_arm64_python3.9.____cpython
          - osx_arm64_python3.10.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.3-6
          channels: conda-forge
          use-mamba: true
      - name: Build conda package
        shell: bash -l {0}
        run: ./.github/workflows/macos-conda-build.sh

