name: conda-build macOS
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  macos-conda-build:
    name: "MacOS - conda-build - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: macos-latest
    env:
      CI: True
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.7']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - uses: xhochy/setup-miniconda@custom_channels
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-4/Miniforge3-4.8.3-4-MacOSX-x86_64.sh
          mamba-version: "*"
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          channels: ***REMOVED***,conda-forge
          custom_channels.***REMOVED***: https://${{ secrets.***REMOVED*** }}:${{ secrets.***REMOVED*** }}@conda.***REMOVED***
      - name: Run Unit Tests
        run: ./.github/workflows/macos-conda-build.sh

