name: conda-build macOS
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  macos-conda-build:
    name: "MacOS - conda-build - ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: macos-latest
    env:
      CI: True
      CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
      CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - osx_64_python3.7.____cpython
          - osx_64_python3.8.____cpython
          - osx_64_python3.9.____cpython
          - osx_arm64_python3.8.____cpython
          - osx_arm64_python3.9.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - name: Create .condarc
        shell: bash -l {0}
        run: |
          sed -ie "s/CONDA_CHANNEL_UPLOAD_USER/${CONDA_CHANNEL_UPLOAD_USER}/g" .github/workflows/.condarc
          sed -ie "s/CONDA_CHANNEL_UPLOAD_PASSWORD/${CONDA_CHANNEL_UPLOAD_PASSWORD}/g" .github/workflows/.condarc
        env:
          CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
          CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      - uses: conda-incubator/setup-miniconda@723ab12c1d66bb893c5ac701f8e387f00b24549e
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.0-4/Miniforge3-4.9.0-4-MacOSX-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          mamba-version: "*"
          channels: quantco_main,conda-forge
          condarc-file: .github/workflows/.condarc
      - name: Run Unit Tests
        shell: bash -l {0}
        run: ./.github/workflows/macos-conda-build.sh

