name: conda-build macOS
on:
  push:
    paths:
      - '.github/**'
      - 'conda.recipe/**'
jobs:
  macos-conda-build:
    name: "MacOS - conda-build - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: macos-latest
    env:
      CI: True
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      ***REMOVED***: ${{ secrets.***REMOVED*** }}
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - osx_64_python3.7.____cpython.yaml
          - osx_64_python3.8.____cpython.yaml
          - osx_64_python3.9.____cpython.yaml
          - osx_arm64_python3.8.____cpython.yaml
          - osx_arm64_python3.9.____cpython.yaml
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - name: Create .condarc
        shell: bash -l {0}
        run: |
          sed -ie "s/***REMOVED***/${***REMOVED***}/g" .github/workflows/.condarc
          sed -ie "s/***REMOVED***/${***REMOVED***}/g" .github/workflows/.condarc
        env:
          ***REMOVED***: ${{ secrets.***REMOVED*** }}
          ***REMOVED***: ${{ secrets.***REMOVED*** }}
      - uses: conda-incubator/setup-miniconda@723ab12c1d66bb893c5ac701f8e387f00b24549e
        with:
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.0-4/Miniforge3-4.9.0-4-MacOSX-x86_64.sh
          allow-softlinks: true
          show-channel-urls: true
          use-only-tar-bz2: true
          mamba-version: "*"
          channels: ***REMOVED***,conda-forge
          condarc-file: .github/workflows/.condarc
      - name: Run Unit Tests
        shell: bash -l {0}
        run: ./.github/workflows/macos-conda-build.sh

