name: Deploy on tag
on:
  push:
    tags:
      - '*'

jobs:
  linux-deployment:
    name: "Linux - deployment - Python ${{ matrix.PYTHON_VERSION }} - ${{ matrix.GLM_ARCHITECTURE }}"
    runs-on: ubuntu-latest
    env:
      CI: True
      CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
      CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6', '3.7', '3.8']
        GLM_ARCHITECTURE: ['default', 'skylake']
    steps:
      - name: Docker login
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.FQ_GH_TOKEN }}
      - name: Pull image
        run: docker pull docker.pkg.github.com/quantco/miniforge3-qc-dev/miniconda3-qc-base:latest
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Fetch all
        run: git fetch --prune --unshallow
      - name: Build and upload conda package
        uses: ./.github/actions/deployment
        with:
          python_version: ${{ matrix.PYTHON_VERSION }}
          glm_architecture: ${{ matrix.GLM_ARCHITECTURE }}

  macos-deployment:
    name: "MacOS - deployment - Python ${{ matrix.PYTHON_VERSION }} - ${{ matrix.GLM_ARCHITECTURE }}"
    runs-on: macos-latest
    env:
      CI: True
      CONDA_CHANNEL_UPLOAD_USER: ${{ secrets.CONDA_CHANNEL_UPLOAD_USER }}
      CONDA_CHANNEL_UPLOAD_PASSWORD: ${{ secrets.CONDA_CHANNEL_UPLOAD_PASSWORD }}
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - osx_64_python3.7_default.____cpython
          - osx_64_python3.7_skylake.____cpython
          - osx_64_python3.8_default.____cpython
          - osx_64_python3.8_skylake.____cpython
          - osx_64_python3.9_default.____cpython
          - osx_64_python3.9_skylake.____cpython
          - osx_arm64_python3.8.____cpython
          - osx_arm64_python3.9.____cpython
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@723ab12c1d66bb893c5ac701f8e387f00b24549e
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.9.2-5
          use-mamba: true
          condarc-file: .github/workflows/.condarc
      - name: Build and upload conda package
        shell: bash -l {0}
        run: ./.github/workflows/macos-tag.sh
